### ISSUE TITLE
Add "Zoom to" function

### ISSUE THREAD

**Issue by Orv** [kn6plv/NewMeshMap#14]
Add a "zoom to" function to locate a specific node.   Zoom into  maybe 20 miles of it.

**Comment by aanon4** [comment]
Done. Called it 'find' because ... well ... it finds things.

**Comment by Orv** [comment]
Good.  But needs to trim trailing spaces.  Can't find node if they exist in string

**Comment by Orv** [comment]
Is it possible to add search for place names?  E.g. "Phoenix"?

**Comment by aanon4** [comment]
I can trim the whitespace.

What are you hoping for with place names? Is there a free services I could use to map something to a lat/lon?

**Comment by aanon4** [comment]
Looks like Geoapify has a free tier with reasonable limits.

**Comment by aanon4** [comment]
Okay. Give that a whirl

**Comment by Orv** [comment]
Don't know if Google's service is free or not:  https://developers.google.com/maps/documentation/geocoding/overview

**Comment by Orv** [comment]
At first pass, looks good!

**Comment by Orv** [comment]
It can find a town, OK - but what are the requirements for finding an address?  It doesn't seem to like mine.

**Comment by aanon4** [comment]
The service takes a free form address and send me back coordinates. What address did you try? I tried various things and it seemed pretty good.

**Comment by aanon4** [comment]
So when I type your address in, I get a single point rather than a box returned .. so the code now handles that case. Let me know how that works for you.
