### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jeepnjonny** [kn6plv/NewMeshMap#15]
the old project had a user install some supporting libraries. What's required to install this version? I've cloned the project but get nothing but the top left menu bar.

**Comment by aanon4** [comment]
I added some instructions to the README.

**Comment by jeepnjonny** [comment]
Thank you! With that I was able to get it setup and working on my network in Idaho

**Comment by aanon4** [comment]
Fantastic. Looking at my supernode map (https://worldmap.bayareamesh.us/#5.39/47.027/-113.234), I dont see you folks on it (unless I'm mistaken)? Any interest in getting connected?

**Comment by jeepnjonny** [comment]
We could get connected. We don't have any supernodes defined or setup.
Still mostly tunnels at this point, with only a couple of RF connections,
but we have 2 repeater sites covering areas.Any assistance understanding
supernodes would be appreciated!

-Jon Glauser

**Comment by aanon4** [comment]
Send me email at tim.j.wilkinson@gmail.com and we can work out the details.
