### ISSUE TITLE
Text not readable

### ISSUE THREAD

**Issue by Orv** [kn6plv/NewMeshMap#2]
The captions on the functions in the lower RH corner of the menu box are too small to easily read.

**Comment by aanon4** [comment]
So this text was super small in the old map too. I can bump the size up, or maybe I should add something different to the top/left menu bar (currently just has the map selector up there)?

**Comment by Orv** [comment]
Either works for me - a separate menu for map functions is a good idea.

**Comment by aanon4** [comment]
Move these to top/left icons.
