### ISSUE TITLE
Add range & bearing function

### ISSUE THREAD

**Issue by Orv** [kn6plv/NewMeshMap#3]
Add range & bearing function, similar to that used at https://mapping.kg6wxc.net/meshmap/#8/33.970/-118.200
![distance](https://github.com/kn6plv/NewMeshMap/assets/1124405/28f3477c-438f-44af-9cbe-7bc5e1beaf3d)

**Comment by aanon4** [comment]
Added measuring tool.

**Comment by Orv** [comment]
Works as expected.   Can some keystroke be added to terminate the measuring function?   As of now, you have to return your cursor to the measurement tool and click it.

**Comment by aanon4** [comment]
Like escape to terminate it?

**Comment by Orv** [comment]
ESC would work nicely, yes.

**Comment by aanon4** [comment]
Done
