### ISSUE TITLE
Add map display mode

### ISSUE THREAD

**Issue by Orv** [kn6plv/NewMeshMap#5]
to the Map | Satellite selection, add a choice of topological display

**Comment by aanon4** [comment]
There's a list here of the options available. Please take a look -

https://docs.mapbox.com/api/maps/styles/#classic-mapbox-styles

**Comment by Orv** [comment]
https://www.mapbox.com/maps/outdoors seems like it would be the most suitable.

**Comment by aanon4** [comment]
Added.
