### ISSUE TITLE
Suggestion: Use OSM

### ISSUE THREAD

**Issue by r1de** [kn6plv/NewMeshMap#8]
Just a suggestion from experience, it could be different now:
Using Mapbox for the tiles can be problematic.
My very first MeshMap used MapBox and one day I got a nice email stating that if I wanted to continue using those tiles I had to cough up quite a bit of $.
Needless to say, I immediately switched to using OSM ~~maps~~ tiles.

YMMV

73 KG6WXC

**Comment by aanon4** [comment]
So that is the big open question. The MapBox stuff is very nice and the use of opengl (webgl?) makes for a much better mapping experience in what can be done. But 50K map loads / month may make it unviable. We will see I suppose.

**Comment by aanon4** [comment]
So it looks like the project I need is MapLibre which is a drop in replacement for MapBox. Now I just need to find some equivalent and free maps.

**Comment by aanon4** [comment]
Okay. Switched to the new library with a couple of OSM maps (standard and topology). Cant find anyone serving satellite images for now.

**Comment by r1de** [comment]
here are some Satellite imagery URLs to try Tim:
//basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/{z}/{y}/{x}

This one contains street info as well as the imagery:
//basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/{z}/{y}/{x}

They aint the greatest, but they work.
