### ISSUE TITLE
Link info on map

### ISSUE THREAD

**Issue by Orv** [kn6plv/NewMeshMap#9]
On the KG6WXC maps, when you click on a link line, a popup appears listing the nodes on each end of the link.  In a map of a crowded urban area, it's a handy tool to have.   Would be nice to incorporate it on this map.

**Comment by aanon4** [comment]
Yeah, my old map did this too (although they were frustrating difficult to click on). I'll see how easy it is to add.

**Comment by Orv** [comment]
Yes, hovering on the line took a lot of patience.   Wonder if the "landing zone" could somehow be expanded?

**Comment by aanon4** [comment]
Done.

**Comment by Orv** [comment]
Works but would be nice if hand cursor changes to pointing finger when hover has found the link.

**Comment by aanon4** [comment]
Not supported by the api I'm afraid.

**Comment by Orv** [comment]
Bummer...
